# Generated by Django 4.1.5 on 2023-02-02 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplyapp', '0002_productmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='productmodel',
        ),
    ]
