# Generated by Django 4.1.5 on 2023-02-02 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplyapp', '0004_productmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='productmodel',
        ),
    ]
