# Generated by Django 4.1.5 on 2023-02-08 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplyapp', '0008_buymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='regmodel',
        ),
    ]
