# Generated by Django 4.1.5 on 2023-02-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplyapp', '0010_regmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='buymodel',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
