# Generated by Django 4.1.5 on 2023-02-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplyapp', '0012_remove_buymodel_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='uid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlistmodel',
            name='uid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
