# Generated by Django 4.1.5 on 2023-02-09 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplyapp', '0013_cartmodel_uid_wishlistmodel_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='buymodel',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
