# Generated by Django 4.1.5 on 2023-02-09 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplyapp', '0014_buymodel_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='buymodel',
        ),
    ]
