# Generated by Django 4.1.5 on 2023-02-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplyapp', '0016_buymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=60)),
                ('image', models.FileField(upload_to='supplyapp/static')),
            ],
        ),
    ]
