# Generated by Django 4.1.5 on 2023-02-09 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplyapp', '0018_alter_feedmodel_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='buymodel',
        ),
    ]
