# Generated by Django 4.1.7 on 2023-05-17 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplyapp', '0022_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='buymodel',
        ),
        migrations.DeleteModel(
            name='cartmodel',
        ),
        migrations.DeleteModel(
            name='feedmodel',
        ),
        migrations.DeleteModel(
            name='logmodel',
        ),
        migrations.DeleteModel(
            name='productmodel',
        ),
        migrations.DeleteModel(
            name='regmodel',
        ),
        migrations.DeleteModel(
            name='shoplogmodel',
        ),
        migrations.DeleteModel(
            name='shopregmodel',
        ),
        migrations.DeleteModel(
            name='wishlistmodel',
        ),
    ]
